language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install && npm install gitbook -g && npm install -g gitbook-cli

script:
  - sh build_gitbook.sh
  - hexo clean && hexo g && cd ./public

after_script:
  - sh push_master.sh
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - GH_REF: github.com/zhongmingmao/zhongmingmao.github.io.git

notifications:
  email:
    recipients:
      - zhongmingmao0625@gmail.com
